import Link from 'next/link';
import QuoteCalculator from '@/components/QuoteCalculator';
import TrackingDemo from '@/components/TrackingDemo';
export default function Home(){return <main>
<section className="hero"><div className="container hero-grid"><div><p className="eyebrow">USA → Guyana logistics platform</p><h1>Shop the world.<br/>Delivered to Guyana.</h1><p className="hero-copy">Your U.S. shipping address, transparent quotes, package tracking, consolidation, and local delivery—all in one place.</p><div className="actions"><Link className="button" href="/register">Get your free address</Link><Link className="button secondary" href="/tracking">Track a package</Link></div><div className="trust-row"><span>✓ Transparent pricing</span><span>✓ Package photos</span><span>✓ Automated updates</span></div></div><div className="hero-panel"><div className="mini-label">Your virtual locker</div><h3>GY000145</h3><div className="stats"><div><b>4</b><span>In Florida</span></div><div><b>2</b><span>In transit</span></div><div><b>1</b><span>Ready</span></div></div><div className="package-item"><span>📦</span><div><b>Amazon package</b><small>Quote ready</small></div><strong>5.2 lb</strong></div></div></div></section>
<section className="section"><div className="container"><p className="eyebrow dark-text">Everything you need</p><h2>One platform from checkout to your doorstep</h2><div className="cards"><article><span>📬</span><h3>Package forwarding</h3><p>Receive a unique customer ID and U.S. shipping address.</p></article><article><span>✈️</span><h3>Air and ocean freight</h3><p>Choose the service that fits your timeline and budget.</p></article><article><span>🛍️</span><h3>Shop For Me</h3><p>Send us a product link and our team can purchase it for you.</p></article><article><span>🚚</span><h3>Local delivery</h3><p>Pickup or request last-mile delivery in Guyana.</p></article></div></div></section>
<section className="section alt"><div className="container split"><div><p className="eyebrow dark-text">Know before you ship</p><h2>Get a transparent estimate</h2><p>Choose a product category, enter its weight and value, and view an estimated total. Rates are planning values and remain editable as verified carrier costs are obtained.</p></div><QuoteCalculator/></div></section>
<section className="section"><div className="container split"><TrackingDemo/><div><p className="eyebrow dark-text">Stay informed</p><h2>Track every major milestone</h2><p>Customers can follow packages from arrival at the Florida warehouse through customs and final delivery.</p><Link className="text-link" href="/tracking">Open tracking →</Link></div></div></section>
<section className="section cta"><div className="container"><h2>Ready to open your Shop2GY locker?</h2><p>Create a demo account and receive a unique customer ID.</p><Link className="button gold" href="/register">Create account</Link></div></section>
</main>}
